### ISSUE TITLE
Detecting trivial solutions

### ISSUE THREAD

**Issue by mappum** [xenoncat/equihash-xenon#5]
@xenoncat Thanks for your awesome solution algorithm, and the awesome writeup explaining how it works.  I've now implemented most of it, but I still haven't added a way to remove trivial solutions. Could you explain your method of efficiently detecting these? Thank you! 👍

**Comment by xenoncat** [comment]
Hi. To detect trivial solutions, just check if the intermediate XOR result is zero.

**Comment by mappum** [comment]
Maybe I'm misunderstanding something, but that won't always work. We know that `(a^x) ^ (a^y)` is equivalent to `x ^ y`, so in that case two pairs that have index `a` would XOR together to something that isn't 0.

**Comment by mappum** [comment]
Nevermind, I tried your solution and see that this eliminates enough trivial solutions to prevent an explosion of new trivial collisions being created. Thanks!
