### ISSUE TITLE
running solver_avx2: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by lowagner** [xenoncat/equihash-xenon#9]
on linux x86_64, i run:
```
cd Linux/demo
make
./solver_avx2
```
and get
```
Reading input.bin
Running solver...
Illegal instruction (core dumped)
```

for whatever reason, solver_avx1 seems to work.

this seems to also be the case if i run `fasm equihash_avx?.asm -m 400000` on the asm parts, and copy in their resulting .o files.

**Comment by xenoncat** [comment]
The error message means that your CPU does not support AVX2 instruction set.
This is the reason for writing solver_avx1, to support older CPUs.

**Comment by lowagner** [comment]
ok, thanks!
